### ISSUE TITLE
[FR] support benchmarking max memory usage

### ISSUE THREAD

**Issue by NightMachinery** [Lateralus138/bench-cli#3]
PS: The readme would benefit from some more example usages, preferably in text (not images), and situated at the top.

**Comment by Lateralus138** [comment]
Your issue title is vague with no details so I don't have much to go on and this is a near redundant project as I have a newer version written in a different language ready for release and an even newer version coming in the near future so I really have no plans on looking into this anytime soon nor even know if I'll look into at all if I eventually archive this project. I only still have this project up for my personal use when I need a quick version of this tool in a temporary environment where I'm not already set up. Once my other tools are up here and released I'll be archiving this project and have no intention of fixing or releasing a new  version.

Sorry I can't help you, especially right now.
